<script src="{{ asset('assets/template-admin/vendor/libs/jquery/jquery.js') }}"></script>
<script src="{{ asset('assets/template-admin/vendor/libs/popper/popper.js') }}"></script>
<script src="{{ asset('assets/template-admin/vendor/js/bootstrap.js') }}"></script>
<script src="{{ asset('assets/template-admin/vendor/js/helpers.js') }}"></script>
<script src="{{ asset('assets/template-admin/js/config.js') }}"></script>
<script src="{{ asset('assets/template-admin/vendor/libs/perfect-scrollbar/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('assets/template-admin/vendor/js/menu.js') }}"></script>
<script src="{{ asset('assets/template-admin/vendor/libs/apex-charts/apexcharts.js') }}"></script>
<script src="{{ asset('assets/template-admin/js/main.js') }}"></script>
<script src="{{ asset('assets/template-admin/js/dashboards-analytics.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
